create table if not exists email_subscribers (
  id integer generated by default as identity primary key,
  email varchar(254) not null unique,
  status varchar(24) not null default 'subscribed',
  preferences text not null default '{}',
  signup_source varchar(80) not null,
  consented_at bigint not null,
  unsubscribed_at bigint,
  referral_code varchar(24) not null unique,
  referring_code varchar(24),
  management_token_hash varchar(64) not null,
  created_at bigint not null,
  updated_at bigint not null,
  constraint ck_email_subscriber_status check (status in ('subscribed','unsubscribed'))
);

create table if not exists email_referrals (
  id integer generated by default as identity primary key,
  referrer_id integer not null references email_subscribers(id) on delete cascade,
  subscriber_id integer not null references email_subscribers(id) on delete cascade,
  referral_code varchar(24) not null,
  created_at bigint not null,
  constraint uq_email_referral_subscriber unique (subscriber_id)
);

create table if not exists email_delivery_logs (
  id integer generated by default as identity primary key,
  subscriber_id integer references email_subscribers(id) on delete set null,
  recipient_email varchar(254) not null,
  email_type varchar(64) not null,
  subject varchar(180) not null,
  provider varchar(40) not null,
  status varchar(24) not null,
  provider_message_id varchar(120),
  error text,
  metadata_json text not null default '{}',
  created_at bigint not null
);

create index if not exists ix_email_subscribers_status on email_subscribers(status);
create index if not exists ix_email_subscribers_referring_code on email_subscribers(referring_code);
create index if not exists ix_email_delivery_logs_subscriber_type on email_delivery_logs(subscriber_id, email_type);
